### ISSUE TITLE
minimal java example

### ISSUE THREAD

**Issue by tischi** [bigdataviewer/bigvolumeviewer-core#4]
Would it be feasible to add a simple minimal Java example of using BigVolumeViewer from Java into the repo?

**Comment by tpietzsch** [comment]
@tischi Do the examples in https://github.com/tpietzsch/jogl-minimal/tree/master/src/test/java/bvv/examples provide enough material?
Can I close this issue?

**Comment by tischi** [comment]
yes. thanks!
